# Generated by Django 2.2.14 on 2020-07-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='start_date',
        ),
    ]
