# Generated by Django 2.2.14 on 2020-07-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200712_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
