# Generated by Django 2.2.14 on 2020-07-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
